# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dimrok/pers/sg

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dimrok/pers/sg

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dimrok/pers/sg/CMakeFiles /home/dimrok/pers/sg/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dimrok/pers/sg/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OpenGLDemo

# Build rule for target.
OpenGLDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OpenGLDemo
.PHONY : OpenGLDemo

# fast build rule for target.
OpenGLDemo/fast:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/build
.PHONY : OpenGLDemo/fast

Comm/shader.o: Comm/shader.cc.o
.PHONY : Comm/shader.o

# target to build an object file
Comm/shader.cc.o:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/Comm/shader.cc.o
.PHONY : Comm/shader.cc.o

Comm/shader.i: Comm/shader.cc.i
.PHONY : Comm/shader.i

# target to preprocess a source file
Comm/shader.cc.i:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/Comm/shader.cc.i
.PHONY : Comm/shader.cc.i

Comm/shader.s: Comm/shader.cc.s
.PHONY : Comm/shader.s

# target to generate assembly for a file
Comm/shader.cc.s:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/Comm/shader.cc.s
.PHONY : Comm/shader.cc.s

GLManager.o: GLManager.cc.o
.PHONY : GLManager.o

# target to build an object file
GLManager.cc.o:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/GLManager.cc.o
.PHONY : GLManager.cc.o

GLManager.i: GLManager.cc.i
.PHONY : GLManager.i

# target to preprocess a source file
GLManager.cc.i:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/GLManager.cc.i
.PHONY : GLManager.cc.i

GLManager.s: GLManager.cc.s
.PHONY : GLManager.s

# target to generate assembly for a file
GLManager.cc.s:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/GLManager.cc.s
.PHONY : GLManager.cc.s

SceneGraph/Node/CameraNode.o: SceneGraph/Node/CameraNode.cc.o
.PHONY : SceneGraph/Node/CameraNode.o

# target to build an object file
SceneGraph/Node/CameraNode.cc.o:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/SceneGraph/Node/CameraNode.cc.o
.PHONY : SceneGraph/Node/CameraNode.cc.o

SceneGraph/Node/CameraNode.i: SceneGraph/Node/CameraNode.cc.i
.PHONY : SceneGraph/Node/CameraNode.i

# target to preprocess a source file
SceneGraph/Node/CameraNode.cc.i:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/SceneGraph/Node/CameraNode.cc.i
.PHONY : SceneGraph/Node/CameraNode.cc.i

SceneGraph/Node/CameraNode.s: SceneGraph/Node/CameraNode.cc.s
.PHONY : SceneGraph/Node/CameraNode.s

# target to generate assembly for a file
SceneGraph/Node/CameraNode.cc.s:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/SceneGraph/Node/CameraNode.cc.s
.PHONY : SceneGraph/Node/CameraNode.cc.s

SceneGraph/Node/RootNode.o: SceneGraph/Node/RootNode.cc.o
.PHONY : SceneGraph/Node/RootNode.o

# target to build an object file
SceneGraph/Node/RootNode.cc.o:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/SceneGraph/Node/RootNode.cc.o
.PHONY : SceneGraph/Node/RootNode.cc.o

SceneGraph/Node/RootNode.i: SceneGraph/Node/RootNode.cc.i
.PHONY : SceneGraph/Node/RootNode.i

# target to preprocess a source file
SceneGraph/Node/RootNode.cc.i:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/SceneGraph/Node/RootNode.cc.i
.PHONY : SceneGraph/Node/RootNode.cc.i

SceneGraph/Node/RootNode.s: SceneGraph/Node/RootNode.cc.s
.PHONY : SceneGraph/Node/RootNode.s

# target to generate assembly for a file
SceneGraph/Node/RootNode.cc.s:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/SceneGraph/Node/RootNode.cc.s
.PHONY : SceneGraph/Node/RootNode.cc.s

SceneGraph/Node/SceneNode.o: SceneGraph/Node/SceneNode.cc.o
.PHONY : SceneGraph/Node/SceneNode.o

# target to build an object file
SceneGraph/Node/SceneNode.cc.o:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/SceneGraph/Node/SceneNode.cc.o
.PHONY : SceneGraph/Node/SceneNode.cc.o

SceneGraph/Node/SceneNode.i: SceneGraph/Node/SceneNode.cc.i
.PHONY : SceneGraph/Node/SceneNode.i

# target to preprocess a source file
SceneGraph/Node/SceneNode.cc.i:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/SceneGraph/Node/SceneNode.cc.i
.PHONY : SceneGraph/Node/SceneNode.cc.i

SceneGraph/Node/SceneNode.s: SceneGraph/Node/SceneNode.cc.s
.PHONY : SceneGraph/Node/SceneNode.s

# target to generate assembly for a file
SceneGraph/Node/SceneNode.cc.s:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/SceneGraph/Node/SceneNode.cc.s
.PHONY : SceneGraph/Node/SceneNode.cc.s

SceneGraph/Node/Test/CubeNode.o: SceneGraph/Node/Test/CubeNode.cc.o
.PHONY : SceneGraph/Node/Test/CubeNode.o

# target to build an object file
SceneGraph/Node/Test/CubeNode.cc.o:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/SceneGraph/Node/Test/CubeNode.cc.o
.PHONY : SceneGraph/Node/Test/CubeNode.cc.o

SceneGraph/Node/Test/CubeNode.i: SceneGraph/Node/Test/CubeNode.cc.i
.PHONY : SceneGraph/Node/Test/CubeNode.i

# target to preprocess a source file
SceneGraph/Node/Test/CubeNode.cc.i:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/SceneGraph/Node/Test/CubeNode.cc.i
.PHONY : SceneGraph/Node/Test/CubeNode.cc.i

SceneGraph/Node/Test/CubeNode.s: SceneGraph/Node/Test/CubeNode.cc.s
.PHONY : SceneGraph/Node/Test/CubeNode.s

# target to generate assembly for a file
SceneGraph/Node/Test/CubeNode.cc.s:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/SceneGraph/Node/Test/CubeNode.cc.s
.PHONY : SceneGraph/Node/Test/CubeNode.cc.s

SceneGraph/Node/Test/GenericNode.o: SceneGraph/Node/Test/GenericNode.cc.o
.PHONY : SceneGraph/Node/Test/GenericNode.o

# target to build an object file
SceneGraph/Node/Test/GenericNode.cc.o:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/SceneGraph/Node/Test/GenericNode.cc.o
.PHONY : SceneGraph/Node/Test/GenericNode.cc.o

SceneGraph/Node/Test/GenericNode.i: SceneGraph/Node/Test/GenericNode.cc.i
.PHONY : SceneGraph/Node/Test/GenericNode.i

# target to preprocess a source file
SceneGraph/Node/Test/GenericNode.cc.i:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/SceneGraph/Node/Test/GenericNode.cc.i
.PHONY : SceneGraph/Node/Test/GenericNode.cc.i

SceneGraph/Node/Test/GenericNode.s: SceneGraph/Node/Test/GenericNode.cc.s
.PHONY : SceneGraph/Node/Test/GenericNode.s

# target to generate assembly for a file
SceneGraph/Node/Test/GenericNode.cc.s:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/SceneGraph/Node/Test/GenericNode.cc.s
.PHONY : SceneGraph/Node/Test/GenericNode.cc.s

SceneGraph/Node/Test/ObjParser.o: SceneGraph/Node/Test/ObjParser.cc.o
.PHONY : SceneGraph/Node/Test/ObjParser.o

# target to build an object file
SceneGraph/Node/Test/ObjParser.cc.o:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/SceneGraph/Node/Test/ObjParser.cc.o
.PHONY : SceneGraph/Node/Test/ObjParser.cc.o

SceneGraph/Node/Test/ObjParser.i: SceneGraph/Node/Test/ObjParser.cc.i
.PHONY : SceneGraph/Node/Test/ObjParser.i

# target to preprocess a source file
SceneGraph/Node/Test/ObjParser.cc.i:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/SceneGraph/Node/Test/ObjParser.cc.i
.PHONY : SceneGraph/Node/Test/ObjParser.cc.i

SceneGraph/Node/Test/ObjParser.s: SceneGraph/Node/Test/ObjParser.cc.s
.PHONY : SceneGraph/Node/Test/ObjParser.s

# target to generate assembly for a file
SceneGraph/Node/Test/ObjParser.cc.s:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/SceneGraph/Node/Test/ObjParser.cc.s
.PHONY : SceneGraph/Node/Test/ObjParser.cc.s

SceneGraph/Node/Test/TestNode.o: SceneGraph/Node/Test/TestNode.cc.o
.PHONY : SceneGraph/Node/Test/TestNode.o

# target to build an object file
SceneGraph/Node/Test/TestNode.cc.o:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/SceneGraph/Node/Test/TestNode.cc.o
.PHONY : SceneGraph/Node/Test/TestNode.cc.o

SceneGraph/Node/Test/TestNode.i: SceneGraph/Node/Test/TestNode.cc.i
.PHONY : SceneGraph/Node/Test/TestNode.i

# target to preprocess a source file
SceneGraph/Node/Test/TestNode.cc.i:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/SceneGraph/Node/Test/TestNode.cc.i
.PHONY : SceneGraph/Node/Test/TestNode.cc.i

SceneGraph/Node/Test/TestNode.s: SceneGraph/Node/Test/TestNode.cc.s
.PHONY : SceneGraph/Node/Test/TestNode.s

# target to generate assembly for a file
SceneGraph/Node/Test/TestNode.cc.s:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/SceneGraph/Node/Test/TestNode.cc.s
.PHONY : SceneGraph/Node/Test/TestNode.cc.s

SceneGraph/Scene/Scene.o: SceneGraph/Scene/Scene.cc.o
.PHONY : SceneGraph/Scene/Scene.o

# target to build an object file
SceneGraph/Scene/Scene.cc.o:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/SceneGraph/Scene/Scene.cc.o
.PHONY : SceneGraph/Scene/Scene.cc.o

SceneGraph/Scene/Scene.i: SceneGraph/Scene/Scene.cc.i
.PHONY : SceneGraph/Scene/Scene.i

# target to preprocess a source file
SceneGraph/Scene/Scene.cc.i:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/SceneGraph/Scene/Scene.cc.i
.PHONY : SceneGraph/Scene/Scene.cc.i

SceneGraph/Scene/Scene.s: SceneGraph/Scene/Scene.cc.s
.PHONY : SceneGraph/Scene/Scene.s

# target to generate assembly for a file
SceneGraph/Scene/Scene.cc.s:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/SceneGraph/Scene/Scene.cc.s
.PHONY : SceneGraph/Scene/Scene.cc.s

ShaderManager/ShaderManager.o: ShaderManager/ShaderManager.cc.o
.PHONY : ShaderManager/ShaderManager.o

# target to build an object file
ShaderManager/ShaderManager.cc.o:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/ShaderManager/ShaderManager.cc.o
.PHONY : ShaderManager/ShaderManager.cc.o

ShaderManager/ShaderManager.i: ShaderManager/ShaderManager.cc.i
.PHONY : ShaderManager/ShaderManager.i

# target to preprocess a source file
ShaderManager/ShaderManager.cc.i:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/ShaderManager/ShaderManager.cc.i
.PHONY : ShaderManager/ShaderManager.cc.i

ShaderManager/ShaderManager.s: ShaderManager/ShaderManager.cc.s
.PHONY : ShaderManager/ShaderManager.s

# target to generate assembly for a file
ShaderManager/ShaderManager.cc.s:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/ShaderManager/ShaderManager.cc.s
.PHONY : ShaderManager/ShaderManager.cc.s

ShaderManager/shader.o: ShaderManager/shader.cc.o
.PHONY : ShaderManager/shader.o

# target to build an object file
ShaderManager/shader.cc.o:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/ShaderManager/shader.cc.o
.PHONY : ShaderManager/shader.cc.o

ShaderManager/shader.i: ShaderManager/shader.cc.i
.PHONY : ShaderManager/shader.i

# target to preprocess a source file
ShaderManager/shader.cc.i:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/ShaderManager/shader.cc.i
.PHONY : ShaderManager/shader.cc.i

ShaderManager/shader.s: ShaderManager/shader.cc.s
.PHONY : ShaderManager/shader.s

# target to generate assembly for a file
ShaderManager/shader.cc.s:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/ShaderManager/shader.cc.s
.PHONY : ShaderManager/shader.cc.s

playground.o: playground.cc.o
.PHONY : playground.o

# target to build an object file
playground.cc.o:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/playground.cc.o
.PHONY : playground.cc.o

playground.i: playground.cc.i
.PHONY : playground.i

# target to preprocess a source file
playground.cc.i:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/playground.cc.i
.PHONY : playground.cc.i

playground.s: playground.cc.s
.PHONY : playground.s

# target to generate assembly for a file
playground.cc.s:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/playground.cc.s
.PHONY : playground.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... OpenGLDemo"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Comm/shader.o"
	@echo "... Comm/shader.i"
	@echo "... Comm/shader.s"
	@echo "... GLManager.o"
	@echo "... GLManager.i"
	@echo "... GLManager.s"
	@echo "... SceneGraph/Node/CameraNode.o"
	@echo "... SceneGraph/Node/CameraNode.i"
	@echo "... SceneGraph/Node/CameraNode.s"
	@echo "... SceneGraph/Node/RootNode.o"
	@echo "... SceneGraph/Node/RootNode.i"
	@echo "... SceneGraph/Node/RootNode.s"
	@echo "... SceneGraph/Node/SceneNode.o"
	@echo "... SceneGraph/Node/SceneNode.i"
	@echo "... SceneGraph/Node/SceneNode.s"
	@echo "... SceneGraph/Node/Test/CubeNode.o"
	@echo "... SceneGraph/Node/Test/CubeNode.i"
	@echo "... SceneGraph/Node/Test/CubeNode.s"
	@echo "... SceneGraph/Node/Test/GenericNode.o"
	@echo "... SceneGraph/Node/Test/GenericNode.i"
	@echo "... SceneGraph/Node/Test/GenericNode.s"
	@echo "... SceneGraph/Node/Test/ObjParser.o"
	@echo "... SceneGraph/Node/Test/ObjParser.i"
	@echo "... SceneGraph/Node/Test/ObjParser.s"
	@echo "... SceneGraph/Node/Test/TestNode.o"
	@echo "... SceneGraph/Node/Test/TestNode.i"
	@echo "... SceneGraph/Node/Test/TestNode.s"
	@echo "... SceneGraph/Scene/Scene.o"
	@echo "... SceneGraph/Scene/Scene.i"
	@echo "... SceneGraph/Scene/Scene.s"
	@echo "... ShaderManager/ShaderManager.o"
	@echo "... ShaderManager/ShaderManager.i"
	@echo "... ShaderManager/ShaderManager.s"
	@echo "... ShaderManager/shader.o"
	@echo "... ShaderManager/shader.i"
	@echo "... ShaderManager/shader.s"
	@echo "... playground.o"
	@echo "... playground.i"
	@echo "... playground.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

