# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dimrok/pers/sg

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dimrok/pers/sg

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dimrok/pers/sg/CMakeFiles /home/dimrok/pers/sg/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dimrok/pers/sg/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OpenGLDemo

# Build rule for target.
OpenGLDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OpenGLDemo
.PHONY : OpenGLDemo

# fast build rule for target.
OpenGLDemo/fast:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/build
.PHONY : OpenGLDemo/fast

Comm/shader.o: Comm/shader.cpp.o
.PHONY : Comm/shader.o

# target to build an object file
Comm/shader.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/Comm/shader.cpp.o
.PHONY : Comm/shader.cpp.o

Comm/shader.i: Comm/shader.cpp.i
.PHONY : Comm/shader.i

# target to preprocess a source file
Comm/shader.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/Comm/shader.cpp.i
.PHONY : Comm/shader.cpp.i

Comm/shader.s: Comm/shader.cpp.s
.PHONY : Comm/shader.s

# target to generate assembly for a file
Comm/shader.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/Comm/shader.cpp.s
.PHONY : Comm/shader.cpp.s

GLManager.o: GLManager.cpp.o
.PHONY : GLManager.o

# target to build an object file
GLManager.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/GLManager.cpp.o
.PHONY : GLManager.cpp.o

GLManager.i: GLManager.cpp.i
.PHONY : GLManager.i

# target to preprocess a source file
GLManager.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/GLManager.cpp.i
.PHONY : GLManager.cpp.i

GLManager.s: GLManager.cpp.s
.PHONY : GLManager.s

# target to generate assembly for a file
GLManager.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/GLManager.cpp.s
.PHONY : GLManager.cpp.s

ShaderManager/ShaderManager.o: ShaderManager/ShaderManager.cpp.o
.PHONY : ShaderManager/ShaderManager.o

# target to build an object file
ShaderManager/ShaderManager.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/ShaderManager/ShaderManager.cpp.o
.PHONY : ShaderManager/ShaderManager.cpp.o

ShaderManager/ShaderManager.i: ShaderManager/ShaderManager.cpp.i
.PHONY : ShaderManager/ShaderManager.i

# target to preprocess a source file
ShaderManager/ShaderManager.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/ShaderManager/ShaderManager.cpp.i
.PHONY : ShaderManager/ShaderManager.cpp.i

ShaderManager/ShaderManager.s: ShaderManager/ShaderManager.cpp.s
.PHONY : ShaderManager/ShaderManager.s

# target to generate assembly for a file
ShaderManager/ShaderManager.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/ShaderManager/ShaderManager.cpp.s
.PHONY : ShaderManager/ShaderManager.cpp.s

ShaderManager/shader.o: ShaderManager/shader.cpp.o
.PHONY : ShaderManager/shader.o

# target to build an object file
ShaderManager/shader.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/ShaderManager/shader.cpp.o
.PHONY : ShaderManager/shader.cpp.o

ShaderManager/shader.i: ShaderManager/shader.cpp.i
.PHONY : ShaderManager/shader.i

# target to preprocess a source file
ShaderManager/shader.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/ShaderManager/shader.cpp.i
.PHONY : ShaderManager/shader.cpp.i

ShaderManager/shader.s: ShaderManager/shader.cpp.s
.PHONY : ShaderManager/shader.s

# target to generate assembly for a file
ShaderManager/shader.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/ShaderManager/shader.cpp.s
.PHONY : ShaderManager/shader.cpp.s

Test/Mesh.o: Test/Mesh.cpp.o
.PHONY : Test/Mesh.o

# target to build an object file
Test/Mesh.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/Test/Mesh.cpp.o
.PHONY : Test/Mesh.cpp.o

Test/Mesh.i: Test/Mesh.cpp.i
.PHONY : Test/Mesh.i

# target to preprocess a source file
Test/Mesh.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/Test/Mesh.cpp.i
.PHONY : Test/Mesh.cpp.i

Test/Mesh.s: Test/Mesh.cpp.s
.PHONY : Test/Mesh.s

# target to generate assembly for a file
Test/Mesh.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/Test/Mesh.cpp.s
.PHONY : Test/Mesh.cpp.s

Test/cTriangle.o: Test/cTriangle.cpp.o
.PHONY : Test/cTriangle.o

# target to build an object file
Test/cTriangle.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/Test/cTriangle.cpp.o
.PHONY : Test/cTriangle.cpp.o

Test/cTriangle.i: Test/cTriangle.cpp.i
.PHONY : Test/cTriangle.i

# target to preprocess a source file
Test/cTriangle.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/Test/cTriangle.cpp.i
.PHONY : Test/cTriangle.cpp.i

Test/cTriangle.s: Test/cTriangle.cpp.s
.PHONY : Test/cTriangle.s

# target to generate assembly for a file
Test/cTriangle.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/Test/cTriangle.cpp.s
.PHONY : Test/cTriangle.cpp.s

Test/material.o: Test/material.cpp.o
.PHONY : Test/material.o

# target to build an object file
Test/material.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/Test/material.cpp.o
.PHONY : Test/material.cpp.o

Test/material.i: Test/material.cpp.i
.PHONY : Test/material.i

# target to preprocess a source file
Test/material.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/Test/material.cpp.i
.PHONY : Test/material.cpp.i

Test/material.s: Test/material.cpp.s
.PHONY : Test/material.s

# target to generate assembly for a file
Test/material.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/Test/material.cpp.s
.PHONY : Test/material.cpp.s

playground.o: playground.cpp.o
.PHONY : playground.o

# target to build an object file
playground.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/playground.cpp.o
.PHONY : playground.cpp.o

playground.i: playground.cpp.i
.PHONY : playground.i

# target to preprocess a source file
playground.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/playground.cpp.i
.PHONY : playground.cpp.i

playground.s: playground.cpp.s
.PHONY : playground.s

# target to generate assembly for a file
playground.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGLDemo.dir/build.make CMakeFiles/OpenGLDemo.dir/playground.cpp.s
.PHONY : playground.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... OpenGLDemo"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Comm/shader.o"
	@echo "... Comm/shader.i"
	@echo "... Comm/shader.s"
	@echo "... GLManager.o"
	@echo "... GLManager.i"
	@echo "... GLManager.s"
	@echo "... ShaderManager/ShaderManager.o"
	@echo "... ShaderManager/ShaderManager.i"
	@echo "... ShaderManager/ShaderManager.s"
	@echo "... ShaderManager/shader.o"
	@echo "... ShaderManager/shader.i"
	@echo "... ShaderManager/shader.s"
	@echo "... Test/Mesh.o"
	@echo "... Test/Mesh.i"
	@echo "... Test/Mesh.s"
	@echo "... Test/cTriangle.o"
	@echo "... Test/cTriangle.i"
	@echo "... Test/cTriangle.s"
	@echo "... Test/material.o"
	@echo "... Test/material.i"
	@echo "... Test/material.s"
	@echo "... playground.o"
	@echo "... playground.i"
	@echo "... playground.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

